version: "3.7"

services:
  store:
    build:
      context: ./store
      dockerfile: Dockerfile
    volumes:
      - ./store:/usr/src/app
    command: fresh
    ports:
      - 8080:8080
    depends_on:
      - db-store
      - redis-store
    working_dir: /usr/src/app
    restart: unless-stopped
  db-store:
    image: postgres:12
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=12345
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /db:/var/lib/postgresql/data
  redis-store:
    image: redis:6.0
    ports:
      - 6379:6379
